# Generated by Django 5.1.15 on 2026-09-18 02:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Producto/Insumo')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo Unitario (S/)')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Stock Actual')),
                ('stock_minimo_alerta', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10, verbose_name='Stock Mínimo de Alerta')),
                ('unidad_medida', models.CharField(default='unidades', max_length=50, verbose_name='Unidad de Medida')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Producto / Insumo',
                'verbose_name_plural': 'Productos / Insumos',
                'db_table': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada por Compra'), ('SALIDA_CONSUMO_SERVICIO', 'Salida por Consumo en Servicio'), ('AJUSTE_POSITIVO', 'Ajuste Físico Positivo'), ('AJUSTE_NEGATIVO', 'Ajuste Físico Negativo')], max_length=35, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario al Asiento (S/)')),
                ('referencia_tipo', models.CharField(default='AJUSTE_MANUAL', max_length=50, verbose_name='Tipo de Referencia')),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Referencia')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción / Glosa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventory.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'movimientos_inventario',
                'ordering': ['-fecha_registro', '-id'],
            },
        ),
    ]
