# Generated by Django 5.1.15 on 2026-09-18 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=150, verbose_name='Especialidad')),
                ('foto_url', models.CharField(blank=True, default='', max_length=500, verbose_name='URL de Fotografía')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('cabina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terapeutas', to='cabins.cabina', verbose_name='Cabina Habitual')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terapeuta', to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de Usuario')),
            ],
            options={
                'verbose_name': 'Terapeuta',
                'verbose_name_plural': 'Terapeutas',
                'db_table': 'terapeutas',
                'ordering': ['id'],
            },
        ),
    ]
