# Generated by Django 5.1.15 on 2026-09-18 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_piel', models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo de Piel / Diagnóstico')),
                ('alergias_conocidas', models.TextField(blank=True, default='', verbose_name='Alergias o Contraindicaciones')),
                ('notas_terapeuta', models.TextField(blank=True, default='', verbose_name='Notas de Evolución y Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_atencion', to='appointments.cita', verbose_name='Cita Asociada')),
            ],
            options={
                'verbose_name': 'Ficha de Atención Clínica',
                'verbose_name_plural': 'Fichas de Atención Clínica',
                'db_table': 'fichas_atencion',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='ServicioAdicionalAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario_historico', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario Histórico (S/)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal (S/)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ficha_atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_adicionales', to='attention.fichaatencion', verbose_name='Ficha de Atención')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicio', verbose_name='Servicio Adicional')),
            ],
            options={
                'verbose_name': 'Servicio Adicional en Atención',
                'verbose_name_plural': 'Servicios Adicionales en Atención',
                'db_table': 'servicios_adicionales_atencion',
            },
        ),
    ]
