# Generated by Django 5.1.15 on 2026-09-18 02:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabins', '0001_initial'),
        ('clients', '0001_initial'),
        ('marketing', '0001_initial'),
        ('services', '0001_initial'),
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_reserva', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Código de Reserva')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha de Cita')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal (S/)')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Descuento (S/)')),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto Total (S/)')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('YAPE', 'Yape'), ('PLIN', 'Plin')], default='EFECTIVO', max_length=20, verbose_name='Método de Pago')),
                ('codigo_cupon_aplicado', models.CharField(blank=True, default='', max_length=50, verbose_name='Cupón Aplicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('cabina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='cabins.cabina', verbose_name='Cabina')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='clients.cliente', verbose_name='Cliente')),
                ('promocion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='marketing.promocion', verbose_name='Promoción Aplicada')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='services.servicio', verbose_name='Servicio Base')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='therapists.terapeuta', verbose_name='Terapeuta')),
            ],
            options={
                'verbose_name': 'Cita / Reserva',
                'verbose_name_plural': 'Citas / Reservas',
                'db_table': 'citas',
                'ordering': ['-fecha', '-hora_inicio'],
                'indexes': [models.Index(fields=['fecha', 'terapeuta', 'hora_inicio', 'hora_fin', 'estado'], name='idx_cita_terapeuta_slot'), models.Index(fields=['fecha', 'cabina', 'hora_inicio', 'hora_fin', 'estado'], name='idx_cita_cabina_slot'), models.Index(fields=['cliente', 'fecha', 'estado'], name='idx_cita_cliente_fecha')],
            },
        ),
    ]
