# Generated by Django 5.1.15 on 2026-09-18 02:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('precio_publico', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio Público (S/)')),
                ('duracion_min', models.PositiveIntegerField(default=60, verbose_name='Duración (minutos)')),
                ('imagen_url', models.CharField(blank=True, default='', max_length=500, verbose_name='URL de Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Servicio / Tratamiento',
                'verbose_name_plural': 'Servicios / Tratamientos',
                'db_table': 'servicios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RecetaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Cantidad Requerida por Atención')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas_usadas', to='inventory.producto', verbose_name='Insumo / Producto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='services.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Receta de Servicio (Insumo)',
                'verbose_name_plural': 'Recetas de Servicios (Insumos)',
                'db_table': 'recetas_servicio',
                'unique_together': {('servicio', 'producto')},
            },
        ),
    ]
