# Generated by Django 5.1.15 on 2026-09-18 02:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso por Cita / Servicio'), ('INGRESO_EXTRA', 'Ingreso Extraordinario'), ('EGRESO', 'Egreso / Devolución / Gasto')], default='INGRESO', max_length=20, verbose_name='Tipo de Movimiento')),
                ('concepto', models.CharField(blank=True, default='', max_length=200, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto (S/)')),
                ('metodo_pago', models.CharField(default='EFECTIVO', max_length=20, verbose_name='Método de Pago')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción / Glosa')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='appointments.cita', verbose_name='Cita Asociada')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'db_table': 'movimientos_caja',
                'ordering': ['-fecha_registro', '-id'],
            },
        ),
    ]
