# Generated by Django 5.1.15 on 2026-09-18 02:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título de la Promoción')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('codigo_cupon', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código de Cupón')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Porcentaje de Descuento (%)')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Promoción / Cupón',
                'verbose_name_plural': 'Promociones / Cupones',
                'db_table': 'promociones',
                'ordering': ['-id'],
            },
        ),
    ]
