# Generated by Django 5.1.15 on 2026-09-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Cabina')),
                ('tipo', models.CharField(max_length=100, verbose_name='Especialidad / Tipo')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Cabina',
                'verbose_name_plural': 'Cabinas',
                'db_table': 'cabinas',
                'ordering': ['id'],
            },
        ),
    ]
